CREATE DATABASE tasksdb IF NOT EXISTS;
USER productsdb;
CREATE TABLE IF NOT EXISTS task(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
describe tasksdb;